### ISSUE TITLE
Using git repo for magento instead of S3

### ISSUE THREAD

**Issue by ahmadSaeedGoda** [aws-quickstart/quickstart-magento#66]
I would like to publish a magento online store using this template for creating my infrastructure, but the point is when i use this template it asks me to download the magento source code and then upload it to the form or to S3 bucket and then provide the bucket's URL to this cloudformation stack to be utilized for the deployment.

What if i want to customize the magento code later on? or how to add themes and extensions? from where i can access the source code by my GIT repo?

Furthermore, in case i would like to create a pipeline for CI/CD, how can i achieve that?

Can somebody please help?

**Comment by AmineFinacsys** [comment]
I used this code to build and push the magento2 open source project to a S3 bucket from gitlab repo.
the package job runs composer install to populate /vendor folder.
i archive the whole project, because that's how the .zip file that you can download fro magento2 website is archived.
then i push to a S3 bucket that i created manually from the aws console.
```yml
image: magento/magento-cloud-docker-php:7.2-cli-1.2.2


# Set any variables we need
variables:
  # Configure aws environment variables
  AWS_ACCESS_KEY_ID: "******************S33E"
  AWS_REGION: "us-east-1"
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_SECRET_ACCESS_KEY: "*************************Ytcf"
  S3_BUCKET_NAME: my-s3-bucket-magento

stages:
  - package
  - push

build:
  stage: package
  script:
      - php -v
      - composer install
      - cd ../
      - tar -czf magento2-${CI_BUILD_REF:0:7}.tar.gz magento2 -C magento2 .
      - mv magento2-${CI_BUILD_REF:0:7}.tar.gz magento2
  artifacts:
    name: "magento2-${CI_BUILD_REF:0:7}"
    paths:
      - ./*.tar.gz
    expire_in: 2 hrs

push:
  image: python:latest
  stage: push
  script:
  - pip install awscli  
# empty S3 bucket
  - aws s3 rm s3://$S3_BUCKET_NAME --recursive
  - aws s3 cp ./magento2-${CI_BUILD_REF:0:7}.tar.gz s3://$S3_BUCKET_NAME/magento2-${CI_BUILD_REF:0:7}.tar.gz
  dependencies:
  - build
```
i used ${CI_BUILD_REF:0:7} to version the file, but it is not necessary.
the magento2 version that i used is 2.3
